### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by iLVOEWOCK** [Katsu-MC/ShadowWarps#1]
You should make each warp have a separate delay, but by default 5

**Comment by Katsu-MC** [comment]
It does have a delay.

**Comment by iLVOEWOCK** [comment]
a SEPARATE, warp one can have a 3 second delay warp two can have a 5 second delay

**Comment by Katsu-MC** [comment]
Yea I don’t know you’re confusing me about the delay. There IS A DELAY to all warps.
